### ISSUE TITLE
Hardcoded min-width for the select column breaks the UI

### ISSUE THREAD

**Issue by shashank1010** [sgratzl/lineup-lite#5]
https://github.com/sgratzl/lineup-lite/blob/340dc558e79be22accb6e6f09a12a78888271d4b/packages/hooks/src/hooks/useRowSelectColumn.tsx#L89

Can we take the defaultColumn width and use it instead of the fixed width 20?

**Comment by sgratzl** [comment]
as an alternative, I could implement a new option that allows you to specify the selection column width. Because in most (default) cases the default column width it too wide for a checkbox.

**Comment by shashank1010** [comment]
That would be ideal.
I would had raised a PR but time doesn't support me.

I believe we can also enhance the shift+select logic, I'll probably raise a PR for you to review later this week.
