### ISSUE TITLE
Can we add a custom intermediate checkbox?

### ISSUE THREAD

**Issue by shashank1010** [sgratzl/lineup-lite#7]
It would be great if we can render a custom Intermediate checkbox component.
I have a react-table component in a project that implements material-ui and the native checkbox seems out of place.

**Comment by sgratzl** [comment]
one option would be to not use the default features but not using the `featureRowSelect` but implement a custom selection column

see also: https://github.com/sgratzl/lineup-lite/blob/main/packages/hooks/src/hooks/useRowSelectColumn.tsx

**Comment by shashank1010** [comment]
I'm unsure of what you mean by not using `featureRowSelect`.
I thought about the custom selection column, but the functionality provided by useRowSelect from react-table is missing shift + select multiple rows.

Worst case scenario, I'll write a custom hook to implement the behaviour you have already build :)

**Comment by sgratzl** [comment]
in the next release there will be a ` selectCheckboxComponent={MyCheckBox}` property
